# Generated by Django 5.2.5 on 2025-08-31 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='Passsword',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
    ]
