# Generated by Django 5.2.5 on 2025-08-31 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_rename_name_contact_passsword_remove_contact_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Passsword',
            new_name='passsword',
        ),
    ]
