# Generated by Django 5.2.5 on 2025-08-31 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_rename_passsword_contact_passsword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='passsword',
            new_name='password',
        ),
    ]
